# Generated by Django 2.2.7 on 2019-12-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191201_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
